name: Run puppeteer

on:
  push:
    branches: [main]
  # schedule:
  #   - cron: "0 15 * * *" #日本時間 0:00
  #   - cron: "0 3 * * *" #日本時間 12:00

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    environment:
      name: Config

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Yarn
        run: yarn install

      - name: Build index.ts
        run: yarn build

      - name: Run index.js
        run: node dist/src/index.js

      - name: Git setting
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.USERNAME }}

      - name: Commit files
        run: |
          git add .
          git commit -m "Update Schedule.json"
          git pull origin main
          git push origin main
