name: Run puppeteer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Yarn
        run: yarn install

      - name: Build index.ts
        run: yarn build

      - name: Run index.js
        run: node dist/index.js

      - name: Git setting
        run: |
          git config --local user.email github-actions
          git config --local user.name github-actions@github.com

      - name: Commit files
        run: |
          git add .
          git commit -m "Update Schedule.json"
          git pull origin main
          git push origin main
